name: Latest Medium Articles
on:
  workflow_dispatch:

jobs:
  update-readme-with-medium:
    name: Update this repo's README with latest articles from Medium
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in medium.com articles
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: "https://medium.com/feed/@peterknezek"
          committer_username: ${{ secrets.GIT_COMMITTER_USERNAME }}
          committer_email: ${{ secrets.GIT_COMMITTER_EMAIL }}
